export const KEYWORDS = {
  "access-point": {
    id: "access-point",
    name: "ACCESS POINT",
    type: 'Keyword',
    description: "Part of a Terrain that connects different elevation levels. Models moving through an ACCESS POINT can change their elevation.",
  },
  "active-player": {
    id: "active-player",
    name: "ACTIVE PLAYER",
    type: 'Keyword',
    description: "The player whose turn it is to act.",
  },
  "anti-evade": {
    id: "anti-evade",
    name: "ANTI-EVADE",
    type: 'Keyword',
    description: "ANTI-EVADE (X) - When resolving an attack with this weapon against Enemy Units , the target Unit suffers a -X Modifier to its Evade Roll for this attack (Part 8.7.4 , Step 4).",
  },
  "blocking-terrain": {
    id: "blocking-terrain",
    name: "BLOCKING TERRAIN",
    type: 'Keyword',
    description: "Any terrain piece with an Effective Size of 1 or greater. Blocking Terrain obstructs Line of Sight according to the Cover rules (Part 7.1.1 ).\n\nWhether a model may move through that terrain is determined separately by the movement rules, terrain Size, ACCESS POINTS , Gap Clearance, and any relevant terrain Keywords .",
  },
  "buff": {
    id: "buff",
    name: "BUFF",
    type: 'Keyword',
    description: "BUFF [Characteristic] (X) The Unit gains a bonus of X to the specified Characteristic until the End of the Round.\n\n• Target Number Characteristic (e.g. Armour , Hit ): reduce the value by X (easier to roll).\n\n• Value Characteristic (e.g. Speed , RoA ): increase the value by X .",
  },
  "bulky": {
    id: "bulky",
    name: "BULKY",
    type: 'Keyword',
    description: "This weapon cannot be used to make a Ranged Attack while the Unit is currently Engaged (Part 8.7.3 ).",
  },
  "burrowed": {
    id: "burrowed",
    name: "BURROWED",
    type: 'Keyword',
    description: "• A BURROWED is classified as a Status .",
  },
  "burst-fire": {
    id: "burst-fire",
    name: "BURST FIRE",
    type: 'Keyword',
    description: "BURST FIRE Y\" (X) When making a Ranged Attack against a target Within Y\" of the attacking model, increase this weapon’s RoA by X for that attack.",
  },
  "concentrated-fire": {
    id: "concentrated-fire",
    name: "CONCENTRATED FIRE",
    type: 'Keyword',
    description: "CONCENTRATED FIRE (X) Attacks with this weapon may remove no more than X models as casualties. Once X models have been removed, discard any remaining Total Damage . It is not recorded as a Damage Marker and does not carry over.",
  },
  "controlling-player": {
    id: "controlling-player",
    name: "CONTROLLING PLAYER",
    type: 'Keyword',
    description: "The player who commands a specific Unit, model, or Token. They make all decisions and roll all dice . Certain abilities (e.g., Neural Parasite) can transfer control; the new controller then acts in every respect as though the Unit were their own.",
  },
  "critical-hit": {
    id: "critical-hit",
    name: "CRITICAL HIT",
    type: 'Keyword',
    description: "CRITICAL HIT (X) Move X dice from the Armour Pool directly to the Damage Pool , bypassing Armour. CRITICAL HIT can never move more dice than are in the Armour Pool .",
  },
  "debuff": {
    id: "debuff",
    name: "DEBUFF",
    type: 'Keyword',
    description: "DEBUFF [Characteristic] (X) The Unit suffers a penalty of X to the specified Characteristic until the End of the Round.\n\n• Target Number Characteristic : increase the value by X (harder to roll).\n\n• Value Characteristic : decrease the value by X (minimum 0).",
  },
  "displacement": {
    id: "displacement",
    name: "DISPLACEMENT",
    type: 'Keyword',
    description: "The Leading Model may end a move Overlapping this Token or Unit (overrides Part 7.3.1 ).\n\nIf the Leading Model ends any Move , Deploy , Run , Charge , Disengage , Close Ranks or Special Ability move Overlapping this Token or model, the controlling player of the Leading Model immediately set it in Base-to-Base contact with the Leading Model . If Base-to-Base is not possible, set it as close as possible.",
  },
  "dodge": {
    id: "dodge",
    name: "DODGE",
    type: 'Keyword',
    description: "DODGE (X) When this Unit is targeted by an attack, reduce the number of dice moved from the Armour Pool to the Damage Pool by Surge or CRITICAL HIT by X (minimum 0). Apply during the Resolve Surge step.",
  },
  "entry-edge": {
    id: "entry-edge",
    name: "ENTRY EDGE",
    type: 'Keyword',
    description: "The table edge assigned to a player by the Deployment Card . Units enter the battlefield from this edge when deploying from Reserves .",
  },
  "fighting-rank": {
    id: "fighting-rank",
    name: "FIGHTING RANK",
    type: 'Keyword',
    description: "A model is in the Fighting Rank if it is Within the Engagement Range (1\") of an Enemy model. Models in the Fighting Rank may strike with their Combat Phase weapons . See Part 8.8.1 , Step 2.",
  },
  "first-player-marker": {
    id: "first-player-marker",
    name: "FIRST PLAYER MARKER",
    type: 'Keyword',
    description: "A physical Token used to track which player has initiative. At the start of the game, the winner of the Roll-Off (Part 3.2 ) assigns the First Player Marker to either player for Round 1. The holder of the First Player Marker chooses which player activates first at the start of each Phase. The Marker changes hands in two ways: the first player to Pass during Phase 1 or Phase 2 takes the First Player Marker for the following Phase, and at the end of Phase 4 the Marker is awarded to the player with fewer Victory Points (Part 8.9.6 ). If Victory Points are tied, both players Roll-Off and the winner takes the Marker.",
  },
  "flying": {
    id: "flying",
    name: "FLYING",
    type: 'Keyword',
    description: "Flying Units trade board control (no Mission Markers , no melee) for mobility and immunity to terrain.\n\n• A Flying Unit ignores all terrain for movement purposes. The Leading Model moves point-to-point, measuring horizontally. Other models may pass through a Flying model’s base as if it were not there, and vice versa.\n\n• A Flying Unit is never Engaged . Ground models cannot Engage Flying models , and Flying models cannot Engage other Flying models . A Flying Unit must end its movement at least 1\" away from all Enemy Flying Units .\n\n• Flying model, ignore the Full Cover rule. Direct Cover and the Elevation Dead Zone rules still apply. Assume that Flying Units ’ Effective Size is higher than the Effective Size of any terrain piece on the table.\n\n• A Flying Unit does not benefit from HIGH GROUND Cover (Part 7.1.3 ).\n\n• A Flying Unit cannot Control or Contest Mission Markers (overrides Parts 6.2 and 8.9.1 ).\n\n• A Flying Unit cannot Charge or be Charged .\n\n• A Flying Unit cannot participate in the Combat Phase (Part 8.8 ).\n\n• A Flying Unit ignores elevation. It does not use Access Points . For Cover and Line of Sight purposes, treat a Flying unit's Effective Size as higher than the Effective Size of any terrain piece on the table (Part 7.1.4 ). Terrain does not contribute to a Flying model's Effective Size .\n\n• A Flying Unit moving over Grass does not destroy the Grass terrain piece. If a Flying Unit ends on a Grass terrain piece, it is removed as normal.",
  },
  "grass": {
    id: "grass",
    name: "GRASS",
    type: 'Keyword',
    description: "A terrain piece with a Size of 2 that follows special rules. Unlike other Size 2 terrain, Grass does not block movement but does block Line of Sight , following the standard Cover rules (Part 7.1.1 ).\n\n Grass is destroyed by the passage of war. If a Leading Model ’s path of travel passes through or any model of a Unit ends on a Grass terrain piece during any movement action ( Move , Deploy , Run , Charge , Disengage or Close Ranks ), that Grass terrain piece is immediately removed from the game. It does not return during Cleanup & Refresh and cannot be replaced by any means.\n\nA Flying Unit moving over Grass does not destroy the Grass terrain piece. Flying models pass above the terrain, not through it. If any model of a Flying Unit ends on a Grass terrain piece, it is removed as normal.",
  },
  "heal": {
    id: "heal",
    name: "HEAL",
    type: 'Keyword',
    description: "HEAL (X) Remove X points of accumulated Damage from the Unit (reduce its Damage Marker accordingly). HEAL cannot return Destroyed models - it only reduces existing Damage . See also: RESPAWN .",
  },
  "hidden": {
    id: "hidden",
    name: "HIDDEN",
    type: 'Keyword',
    description: "This Unit cannot be selected as the target of a Ranged Attack or any LoS-requiring Special Ability unless the acting model is Within 4\" of it. A HIDDEN Unit is immune to the IMPACT Keyword . A HIDDEN Unit may make an Evade Roll against every attack targeting it.",
  },
  "hits": {
    id: "hits",
    name: "HITS",
    type: 'Keyword',
    description: "HITS X (Y) The affected Unit suffers X automatic hits . Set X dice directly into the Armour Pool and proceed immediately to Armour Rolls (Part 8.7.4 , Steps 3–4). Treat the Damage characteristic as Y . These hits do not generate Surge.",
  },
  "impact": {
    id: "impact",
    name: "IMPACT",
    type: 'Keyword',
    description: "IMPACT (X) Y Immediately after this Unit completes a successful Charge , check every model in the Fighting Rank or Supporting Rank . For each eligible model, generate X Impact Dice :\n\n• If the model is in the Fighting Rank or Supporting Rank against only one Enemy Unit, all X dice go to that Unit.\n\n• If the model is in the Fighting Rank or Supporting Rank against multiple Enemy Units , the controlling player may split the dice between those Units .\n\nRoll the allocated dice for each target Unit separately (this is the Impact Hit Roll ). For each result of Y or higher, set 1 die into the target’s Armour Pool . Proceed immediately to Armour Rolls . These hits do not generate Surge and treat Damage as 1 .",
  },
  "impassable-terrain": {
    id: "impassable-terrain",
    name: "IMPASSABLE TERRAIN",
    type: 'Keyword',
    description: "A terrain piece is Impassable if it has no Access Point connecting it to an adjacent elevation level. Models cannot move through, onto, or across IMPASSABLE TERRAIN , and no model may end its movement overlapping it. Terrains of sizes 0 and 1 are never considered IMPASSABLE TERRAIN .",
  },
  "indirect-fire": {
    id: "indirect-fire",
    name: "INDIRECT FIRE",
    type: 'Keyword',
    description: "Ranged Attacks with this weapon may ignore Line of Sight when selecting a target and resolving Damage . The target must still be Within Range. If the target is not Visible , it may make an Evade Roll against this attack.",
  },
  "instant": {
    id: "instant",
    name: "INSTANT",
    type: 'Keyword',
    description: "Enemy Units cannot declare or resolve Reaction abilities in response to attacks made with this weapon.",
  },
  "large-x": {
    id: "large-x",
    name: "LARGE (X)",
    type: 'Keyword',
    description: "LARGE (X) When this Unit’s Leading Model moves, it may pass through physical gaps at least X\" wide, regardless of its base size .",
  },
  "locked-in": {
    id: "locked-in",
    name: "LOCKED IN",
    type: 'Keyword',
    description: "LOCKED IN (X) When making a Ranged Attack with this weapon, add X to its RoA if the target Unit has Stationary Status .",
  },
  "long-range": {
    id: "long-range",
    name: "LONG RANGE",
    type: 'Keyword',
    description: "LONG RANGE (X) The maximum Range of this weapon increases to X\" .\n\nMeasure each attacking model’s distance to the target individually:\n\n• Within normal profile Range : attack resolves normally.\n\n• Beyond profile Range but Within X\" : the model suffers a -1 Modifier to its Hit roll .\n\nIf a Batch contains models at both Standard and Long Range , generate the total dice but roll the two groups separately to account for different Hit Target Numbers .",
  },
  "non-lethal-damage": {
    id: "non-lethal-damage",
    name: "NON-LETHAL DAMAGE",
    type: 'Keyword',
    description: "NON-LETHAL DAMAGE (X) The Unit suffers X points of Damage . Add this amount effectively to the Unit’s Damage Marker . Unlike standard Damage , NON-LETHAL DAMAGE does not trigger the Remove Casualties step (Part 8.7.4 , Step 5), even if Total Damage exceeds a model’s HP . If the Unit subsequently suffers standard Damage , the combined Total Damage triggers casualty removal normally.",
  },
  "on-creep": {
    id: "on-creep",
    name: "ON CREEP",
    type: 'Keyword',
    description: "A Friendly or Enemy Ground Zerg Unit is considered to be ON CREEP while it is Within 6\" of any Creep Tumor Token or any model designated as a Source of Creep . While satisfying this condition, the Unit gains the ON CREEP Keyword . This allows the Unit to trigger specific Special Abilities or Upgrades that require this state.",
  },
  "pierce": {
    id: "pierce",
    name: "PIERCE",
    type: 'Keyword',
    description: "PIERCE [TAG] X When attacking a Unit with the specified Combat Tag , treat this weapon’s Damage characteristic as X .",
  },
  "pinpoint": {
    id: "pinpoint",
    name: "PINPOINT",
    type: 'Keyword',
    description: "Ranged Attacks with this weapon may target Engaged Enemy Units , ignoring the standard Engagement Status restriction (overrides Part 8.7.3 , Step 1).",
  },
  "place": {
    id: "place",
    name: "PLACE",
    type: 'Keyword',
    description: "PLACE (X) Choose a Leading Model . Remove it and set it Wholly Within X\" of its starting position. Then remove and replace all other models in the Unit, maintaining Coherency (Part 4.4 ). PLACE ignores Gap Clearance, terrain restrictions, and elevation requirements. The Leading Model is removed and set directly, not moved along a path. However, they must end in a legal position. Models may be set Within the Engagement Range of Enemy models (the Unit becomes Engaged ) unless stated otherwise.",
  },
  "ready": {
    id: "ready",
    name: "READY",
    type: 'Keyword',
    description: "The default state of a Tactical Card or Faction Card . A Ready card is face-up, its abilities are available, and it may be Exhausted to pay resource costs or activate its Special Abilities . All Tactical Cards and Faction Cards begin each Round in the Ready state. Cards that have been Exhausted are returned to Ready during Cleanup & Refresh (Part 8.9.5 ).",
  },
  "stationary": {
    id: "stationary",
    name: "STATIONARY",
    type: 'Keyword',
    description: "At the Start of the Round , all Units gain this Status . A Unit immediately loses this Status if any model in this Unit moves, is moved, or is PLACED for any reason.",
  },
  "precision": {
    id: "precision",
    name: "PRECISION",
    type: 'Keyword',
    description: "PRECISION (X) After rolling to Hit , move up to X failed Attack Dice directly into the Armour Pool . Treat them as successful Hits for all purposes, including Surge .",
  },
  "repeatable": {
    id: "repeatable",
    name: "REPEATABLE",
    type: 'Keyword',
    description: "This ability is exempt from the Once Per Round limit (Part 2.7.1 ). It may be used multiple times per Round and per Activation , provided all Costs and trigger conditions are met each time.",
  },
  "reserves": {
    id: "reserves",
    name: "RESERVES",
    type: 'Keyword',
    description: "A holding area off the battlefield where Units remain until they are deployed. All Units begin the game in Reserves . A Unit in Reserves is part of the player’s army for all purposes - it counts towards Army Building limits and is tracked on the Army Roster - but it is not on the battlefield.\n\nWhile in Reserves , a Unit:\n\n• Cannot be targeted by attacks or abilities unless an ability explicitly states it affects Units in Reserves .\n\n• Cannot use Active Abilities , Passive Abilities , or Reaction Abilities unless the ability explicitly states otherwise.\n\n• Cannot control or contest Mission Markers .\n\n• Does not contribute its Current Supply to the player’s Total Current Supply on the battlefield.\n\n• Retains all equipment, upgrades, and weapon selections assigned during Army Building .\n\nA Unit enters Reserves at the start of the game and leaves Reserves when it is deployed to the battlefield. Some rules may return a Unit to Reserves during play - see Part 8.5.5 ( Units Returned to Reserves ) for how Damage , effects, and Supply are handled when this occurs.\n\nIn the final Round of the game, all Units still in Reserves that are not deployed are treated as Destroyed for scoring purposes (Part 8.10 ).",
  },
  "respawn": {
    id: "respawn",
    name: "RESPAWN",
    type: 'Keyword',
    description: "RESPAWN (X) Return up to X Destroyed models to this Unit.\n\n• The return cannot increase the Unit’s Current Supply Value . Do not return a model if doing so would push the Unit into a higher Supply bracket.\n\n• Set each returned model in Base-to-Base contact with an existing model in the Unit. Returned models cannot be set Within the Engagement Range of any Enemy Unit.\n\n• If a model cannot be set legally, it cannot be returned.",
  },
  "shielded": {
    id: "shielded",
    name: "SHIELDED",
    type: 'Keyword',
    description: "If a Shield value is present on a Unit Card, add it to the H it Points (HP) of the first model. The Unit is Shielded . The Unit loses its Shielded Status when the Total Damage assigned to it exceeds its Shield value or when the first model in the Unit is removed.\n\nThe Shielded Status is referenced by other abilities. Losing Shielded Status does not remove any remaining Hit Points , it only ends effects that require the Unit to be Shielded .",
  },
  "sidearm": {
    id: "sidearm",
    name: "SIDEARM",
    type: 'Keyword',
    description: "When this Unit performs a Ranged Attack or Close Combat Attack , models equipped with this weapon may use it, ignoring the normal restriction of one weapon per model (Part 8.7.3 ). If a model is equipped with multiple SIDEARM weapons, it may use all of them in the same activation.\n\nAttacks made with each SIDEARM must be resolved in separate Batches. Because they are separate Batches, SIDEARM attacks may target a different Enemy Unit than the Unit's other weapons, subject to all standard target eligibility requirements.",
  },
  "supporting-rank": {
    id: "supporting-rank",
    name: "SUPPORTING RANK",
    type: 'Keyword',
    description: "A model is in the Supporting Rank if it is in Base-to-Base contact with a Friendly model from the same Unit that is in the Fighting Rank , but is not itself Within the Engagement Range of an Enemy model. Models in the Supporting Rank may strike with their Combat Phase weapons as though they were in the fight. See Part 8.8.1 , Step 2.",
  },
  "specialist": {
    id: "specialist",
    name: "SPECIALIST",
    type: 'Keyword',
    description: "A Unit may include only one model equipped with this weapon. Multiple upgrades configuring more than one instance of this weapon are not permitted (Part 9.1.7 ).",
  },
  "spillover": {
    id: "spillover",
    name: "SPILLOVER",
    type: 'Keyword',
    description: "Additional hits generated by a Template Weapon that strike models outside the Primary target Unit. When a Blast Template (BT) or Flamer Template (FT) covers models belonging to Units other than the Primary target, those models are resolved as Spillover . Each affected Unit is resolved as a separate Batch . Spillover Batches do not apply Rate of Attack modifiers and do not generate Surge. Spillover may affect both Friendly and Enemy Units . See Part 8.7.6 for the full Template Weapon procedure.",
  },
  "stay-in-play": {
    id: "stay-in-play",
    name: "STAY IN PLAY",
    type: 'Keyword',
    description: "This Token, Marker or Ability Effect persists through Cleanup & Refresh (overrides Part 8.9.5 ). It remains until a specific condition removes it (e.g. destroyed or duration expires).",
  },
  "status": {
    id: "status",
    name: "STATUS",
    type: 'Keyword',
    description: "A category of Keyword representing a temporary or persistent operational mode, condition, or statistic modifier affecting a Unit (e.g. BURROWED , SIEGE MODE ).\n\nA Unit’s active Status is visually tracked using Status Markers set next to the Unit:\n\n• Modes: Use Plastic Markers to track operational shifts (e.g. SIEGE MODE, BURROWED ).  Those Status Markers have STAY IN PLAY .\n\n• Buffs/Debuffs: Use Markers to track temporary changes to characteristics (Blue = Buff , Red = Debuff ).",
  },
  "summon": {
    id: "summon",
    name: "SUMMON",
    type: 'Keyword',
    description: "SUMMON (Unit Name) Set the Leading Model of the named Unit in Base-to-Base contact with the Parent Unit. Set remaining models In Coherency . Models cannot be set Within the Engagement Range of any Enemy Unit.\n\nSet an Activation Marker next to the summoned Unit - it cannot be Activated during the Phase in which it was summoned. In subsequent Phases, this Unit must be Activated immediately after its Parent Unit’s activation ends, before the opponent’s next activation.\n\nThe Summoned Unit cannot be set Within the opponent’s Zone of Influence .\n\nThe player must have sufficient Available Supply . If the Unit’s Current Supply Value would cause Total Current Supply to exceed the Supply Pool , it cannot be Summoned.\n\nIf the Parent is not present on the battlefield, this Unit can be Activated normally.",
  },
  "tactical-mass": {
    id: "tactical-mass",
    name: "TACTICAL MASS",
    type: 'Keyword',
    description: "A Unit has Tactical Mass when its Current Supply Value exceeds the Combined Current Supply Value of all Enemy Units it is Engaged with. A Unit with Tactical Mass ignores the Disengage penalty (Part 8.5.4 ): it may Ranged Attack and Charge normally in the following Assault Phase after Disengaging.",
  },
  "tough": {
    id: "tough",
    name: "TOUGH",
    type: 'Keyword',
    description: "TOUGH (X) When this Unit resolves an Armour Roll , change up to X failed results into successes. Treat them as meeting or exceeding the Armour characteristic - discard them without moving to the Damage Pool .",
  },
  "zone-of-influence": {
    id: "zone-of-influence",
    name: "ZONE OF INFLUENCE",
    type: 'Keyword',
    description: "A restricted area of the battlefield extending 6\" inward from a player’s Entry Edge , as defined by the Deployment Card . Where the Entry Edg e does not run the full length of a table edge, the Zone of Influence is marked using Zone of Influence Markers set at the corners of the Entry Edge .\n\n Units arriving from Reserves cannot end their deployment Within the opponent’s Zone of Influence . This restriction applies to all forms of arrival - whether by standard deployment , transport, or SUMMON (Part 8.3.3 ).\n\nThe Z one of Influence does not affect Units already on the battlefield. It does not restrict movement, block Line of Sight , or interact with any other rule once a Unit has completed its arrival.",
  },
  "friendly": {
    id: "friendly",
    name: "FRIENDLY",
    type: 'Keyword',
    description: "All Units , Tokens , and cards belonging to the Controlling Player are Friendly to one another. In team games , all teammates' Units , Tokens , and cards are also Friendly . A Unit's own models are always Friendly to it. Friendly is the opposite of Enemy and is used throughout the rules to determine targeting restrictions, movement interactions, and ability eligibility.",
  },
  "enemy": {
    id: "enemy",
    name: "ENEMY",
    type: 'Keyword',
    description: "All Units , Tokens , and cards belonging to the opponent are Enemies . In team games , all opposing players' Units , Tokens , and cards are Enemies . A Unit may never target a Friendly Unit with an attack unless a rule explicitly states otherwise. Enemy is the opposite of Friendly and is referenced throughout the rules to determine valid targets, Engagement , and Mission Marker contests.",
  },
  "visible": {
    id: "visible",
    name: "VISIBLE",
    type: 'Keyword',
    description: "A model is Visible to another model if a valid Line of Sight trace can be drawn between them (Part 7.1 ). If the trace does not pass through any Blocking Terrain , the target is Visible without further checks. If the trace passes through Blocking Terrain , apply the Cover rules (Part 7.1.1 )- the target remains Visible unless Full Cover or Direct Cover blocks the Line of Sight .\n\nA model with the HIDDEN Keyword is not Visible to any model more than 4\" away, regardless of Line of Sight .\n\n Visible is a reciprocal state: if Model A is Visible to Model B, then Model B is Visible to Model A.",
  },
  "combat-tags": {
    id: "combat-tags",
    name: "COMBAT TAGS",
    type: 'Keyword',
    description: "Combat Tags are Keywords printed on a Unit Card that identify a Unit's physical nature and tactical class.\n\n Type Tags : Armoured, Biological, Light, Mechanical, Psionic, Flying , and Ground.\n\n• Targeting: Some weapons can fire only at specific Combat Tags (e.g., \"Target: Flying \").\n\n• Surge: A weapon's Surge efficiency triggers only when the target has the Combat Tag listed in the weapon's Surge Type (Part 8.7.4 ).\n\n• Bonuses: Abilities such as ANTI-EVADE (X) or PIERCE (X) often apply only against specific Combat Tags .\n\nNote: The Ground Combat Tag and the GROUND LEVEL elevation (Part 8.5.3 ) are distinct concepts. A Flying Unit standing on the playmat is at GROUND LEVEL but does not have the Ground Combat Tag . Throughout these rules, Ground in bold always refers to the Combat Tag . GROUND LEVEL always refers to elevation.",
  },
  "army-slot": {
    id: "army-slot",
    name: "ARMY SLOT",
    type: 'Keyword',
    description: "Army Slots determine how many and what types of Units may be included in an army. Each Army Slot has a type: Core, Elite, Support, Air, or Hero. Every Unit occupies a number of Army Slots of its designated type equal to its starting Supply Value .\n\nThe Faction Card provides the initial pool of Army Slots . Additional Army Slots are unlocked by purchasing Tactical Cards with Vespene Gas during Army Building (Part 9.1.5 ). Unused Army Slots are lost- they cannot be converted, exchanged, or carried forward.",
  },
  "faction-tags": {
    id: "faction-tags",
    name: "FACTION TAGS",
    type: 'Keyword',
    description: "Faction Tags are Keywords printed on Unit Cards , Tactical Cards , and Faction Cards that identify allegiance.\n\n• Race Tags : Terran , Zerg , Protoss .\n\n• Sub- Faction Tags : Specific broods or organisations, e.g., Kerrigan 's Swarm , Raynor's Raiders .\n\n• Function: During Army Building , a player may include only Units and Tactical Cards whose Faction Tags all appear on the chosen Faction Card . If even one tag on the Unit or Tactical Card does not appear on the Faction Card , that card cannot be included. A Unit with fewer tags than the Faction Card is permitted- it only requires its own tags to be present (Part 9.1.2 ).",
  },
  "special-ability": {
    id: "special-ability",
    name: "SPECIAL ABILITY",
    type: 'Keyword',
    description: "A Special Ability is any named ability printed on a Unit Card , Tactical Card , or Faction Card . Every Special Ability falls into one of three categories: Active Ability , Passive Ability , or Reaction Ability (Part 2.7 ).\n\n• Active Abilities require the Unit to be Activated and are triggered immediately before or after an action. Each named Active Ability may be used once per Round per Unit unless it has the REPEATABLE Keyword.\n\n• Passive Abilities are always in effect as long as the Unit is on the battlefield.\n\n• Reaction Abilities fire in response to a specific trigger. Each player may resolve only one Reaction per Activation, and each named Reaction Ability may be used only once per Round per Unit.\n\nAll three types are inactive while the Unit is in Reserves unless the ability explicitly states otherwise.",
  },
  "reserves": {
    id: "reserves",
    name: "RESERVES",
    type: 'Keyword',
    description: "A holding area off the battlefield where Units remain until they are deployed. All Units begin the game in Reserves .\n\nWhile in Reserves , a Unit:\n\n• Cannot be targeted by attacks or abilities unless an ability explicitly states it affects Units in Reserves .\n\n• Cannot use Active Abilities , Passive Abilities , or Reaction Abilities unless the ability explicitly states otherwise.\n\n• Cannot Control or Contest Mission Markers .\n\n• Does not contribute its Current Supply Value to the player's Total Current Supply on the battlefield.\n\n• Retains all equipment, upgrades, and weapon selections assigned during Army Building .\n\nA Unit leaves Reserves when it is deployed to the battlefield via a Deploy action (Part 8.5.5 ). Some rules may return a Unit to Reserves during play- see Part 8.5.5 for how Damage , effects, and Supply are handled. In the final Round of the game, all Units still in Reserves that are not deployed are treated as Destroyed for scoring purposes (Part 8.10 ).",
  },
  "modifier": {
    id: "modifier",
    name: "MODIFIER",
    type: 'Keyword',
    description: "A Modifier adjusts the Target Number of a roll. Apply all Modifiers before rolling (Part 3.4 ).\n\n• +X Modifier : Makes the roll easier by reducing the Target Number by X.\n\n• -X Modifier : Makes the roll harder by increasing the Target Number by X.\n\n Modifiers from different named sources are cumulative unless otherwise stated. A Target Number can never be modified below 2+ or above 6+ . Modifiers adjust the Target Number, not the dice result. A natural roll of 6 always succeeds and a natural roll of 1 always fails, regardless of Modifiers (Part 3.6 ).\n\nA Modifier is distinct from a Fixed Addition (Part 3.5 ), which generates a value rather than adjusting a Target Number.",
  },
  "wholly-within": {
    id: "wholly-within",
    name: "WHOLLY WITHIN",
    type: 'Keyword',
    description: "A model is Wholly Within a distance only if its entire base sits inside that range- no part of the base may extend beyond the edge. A Unit is Wholly Within a distance only if every model in the Unit satisfies this condition.\n\n Wholly Within is a stricter requirement than Within and is used for Coherency checks (Part 4.4 ), certain ability areas of effect, and Mission Marker eligibility. When a rule specifies Wholly Within , partial overlap is not sufficient.",
  },
  "within": {
    id: "within",
    name: "WITHIN",
    type: 'Keyword',
    description: "A model is Within a distance if any part of its base touches or crosses into that range. A Unit is Within a distance if at least one model in the Unit meets this condition.\n\n Within is a less restrictive requirement than Wholly Within . When a rule specifies Within without the word \"Wholly,\" partial overlap is sufficient.",
  },
  "leading-model": {
    id: "leading-model",
    name: "LEADING MODEL",
    type: 'Keyword',
    description: "The Leading Model is a temporary reference point used to execute a Unit's movement. Whenever a Unit performs a Move , Deploy , Run , Charge , Disengage , Close Ranks , or any action that instructs the Unit to nominate a Leading Model , the Controlling Player selects one model in the Unit.\n\n Move the Leading Model first, measuring its exact path. Then set the remaining models in valid Coherency around the Leading Model 's new position (Part 4.4 ). The Leading Model nomination ends once the action resolves. The Leading Model determines the Unit's Gap Clearance category and interacts with terrain restrictions (Part 4.6 ).",
  },
  "supply-value": {
    id: "supply-value",
    name: "SUPPLY VALUE",
    type: 'Keyword',
    description: "The Supply Value of a Unit is the value shown on the Unit Card's Supply Profile corresponding to the Unit's current model count. A Unit's starting Supply Value is determined during Army Building by the Composition Option selected (Part 9.1.6 ) and defines how many Army Slots the Unit occupies.\n\n Supply Value is a dynamic characteristic- as casualties reduce the model count into a lower bracket on the Supply Profile , the Supply Value decreases. Update immediately when a casualty moves the Unit into a lower bracket. Supply is used for Deployment , Mission Marker Control, Tactical Mass , and scoring.",
  },
  "current-supply-value": {
    id: "current-supply-value",
    name: "CURRENT SUPPLY VALUE",
    type: 'Keyword',
    description: "The Current Supply Value of a Unit is its Supply Value at this moment, based on the number of models remaining in the Unit as shown on the Supply Profile (Part 6.1 ). Update the Current Supply Value immediately whenever a casualty reduces the model count into a lower bracket.\n\nThe Current Supply Value is referenced when checking whether a Unit may be deployed from Reserves (Part 8.3.2 ), when determining Mission Marker Control (Part 8.9.1 ), when evaluating Tactical Mass for Disengage (Part 8.5.4 ), and when calculating Victory Points for Supply-based scoring conditions.",
  },
  "available-supply": {
    id: "available-supply",
    name: "AVAILABLE SUPPLY",
    type: 'Keyword',
    description: "Available Supply is the amount of Supply capacity remaining for new deployments. It equals the current Supply Pool minus the Total Current Supply Value of all Friendly Units on the battlefield (Part 8.3.2 ).\n\nA Unit may only be deployed from Reserves if its Current Supply Value is less than or equal to the Available Supply . At no point may the Total Current Supply of a player's on-table Units exceed the Supply Pool . Units Destroyed or reduced by casualties free up Available Supply for new arrivals. In the final Round of the game, the Supply Pool becomes unlimited and Available Supply restrictions are lifted.",
  },
  "effective-size": {
    id: "effective-size",
    name: "EFFECTIVE SIZE",
    type: 'Keyword',
    description: "A model's Effective Size is equal to its Size characteristic plus the Size of any terrain it is standing on (Part 7.1.2 ).\n\nA model at GROUND LEVEL has an Effective Size equal to its own Size characteristic only. A model on HIGH GROUND (Size 3+) or MID GROUND (Size 1–2) adds the terrain's Size to its own. Terrain pieces set on elevated surfaces stack in the same way- a terrain piece's Effective Size equals its own Size plus the Size of the terrain it stands on.\n\n Effective Size determines which terrain blocks Line of Sight through Full Cover and Direct Cover (Part 7.1.1 ). Flying models are treated as having an Effective Size higher than any terrain piece on the table for Cover purposes (Part 7.1.4 ).",
  },
  "engaged": {
    id: "engaged",
    name: "ENGAGED",
    type: 'Keyword',
    description: "A Ground Unit is Engaged when any of its models is Within 1\" ( Engagement Range ) of any model in an Enemy Ground Unit, provided the following conditions are met (Part 7.2.1 ):\n\n• Combat Tags match: Ground models Engage only Ground models . Flying models cannot be Engaged by any model.\n\n• Terrain does not block: Size 2+ terrain between the models prevents Engagement , even if they are Within 1\" . Models on HIGH GROUND cannot Engage models at GROUND LEVEL , and vice versa.\n\nWhen any model in a Unit is Engaged , the entire Unit is considered Engaged . An Engaged Unit cannot perform a standard Move - it must Disengage (Part 8.5.4 ) or Hold . Engaged Units are also subject to restrictions on Ranged Attacks (Part 8.7.3 ).",
  },
  "engagement-range": {
    id: "engagement-range",
    name: "ENGAGEMENT RANGE",
    type: 'Keyword',
    description: "The Engagement Range extends 1\" horizontally from any model's base. When two Enemy Ground models are Within each other's Engagement Range , they are Engaged (Part 7.2 ).\n\n Engagement Range is measured horizontally from a top-down perspective, ignoring vertical height (Part 4.1 ). It is referenced when resolving Move restrictions (Part 8.5.3 ), Disengage (Part 8.5.4 ), Charge (Part 8.6.2 ), the Fighting Rank (Part 8.8.1 ), and PLACE effects. Melee weapons list E as their Range, indicating they may only strike targets Within the Engagement Range .",
  },
  "unengaged": {
    id: "unengaged",
    name: "UNENGAGED",
    type: 'Keyword',
    description: "A Ground Unit is Unengaged when none of its models is Within 1\" of any Enemy Ground model, or when terrain restrictions (Part 7.2.1 ) prevent valid Engagement despite proximity. Flying Units are always Unengaged .\n\nAn Unengaged Unit may perform a standard Move , Run , Ranged Attack , or Charge without restriction. Only Unengaged Units may be selected to perform a Move action (Part 8.5.2 ).",
  },
  "mission-markers": {
    id: "mission-markers",
    name: "MISSION MARKERS",
    type: 'Keyword',
    description: "Numbered Markers set on the battlefield during Setup at coordinates shown on the Deployment Card . Each Marker is 32mm in diameter and has two sides: Activated or Deactivated . Markers 1 & 3 are Red, Markers 2 & 4 are Blue, and Marker 5 is Neutral.\n\n Mission Markers are the primary scoring mechanism. At the end of each Round, players determine Control of each Marker by comparing the Total Current Supply Value of their eligible contesting Units (Part 8.9.1 ). A Unit may Contest a Mission Marker only if it is on the battlefield, In Coherency , and has at least one model Within 3\" with Line of Sight to the Marker on the same elevation. Flying Units and BURROWED Units cannot Contest or Control Mission Markers .\n\nControl is Sticky - once a player Controls a Marker, it remains under their control until the opponent reclaims it with a higher contesting Supply total. A tied result never transfers control.",
  },
  "line-of-sight-los": {
    id: "line-of-sight-los",
    name: "LINE OF SIGHT (LoS)",
    type: 'Keyword',
    description: "Line of Sight determines what a model can see and, by extension, what it can target with attacks and abilities.\n\nAll Line of Sight checks are resolved from a 2D top-down perspective , looking directly down at the battlefield from above. To check whether a model can see a target, trace an imaginary straight line from any part of the acting model's base to any part of the target model's base. Vertical height is never factored into the trace.\n\nIf the trace does not pass through any Blocking Terrain (any terrain piece with an Effective Size of 1 or greater), the target is Visible . No further checks are required.\n\nIf the trace passes through Blocking Terrain , the target is not automatically hidden . Apply the Cover rules (Part 7.1.1 ) to determine whether that terrain actually blocks the Line of Sight :\n\n• Full Cover : The terrain's Effective Size is equal to or greater than the Effective Size of both the attacker and the target. Line of Sight is blocked.\n\n• Direct Cover : The trace passes through a terrain piece, and either the attacker or the target is Within 1\" of that terrain, provided the terrain's Effective Size is equal to or greater than the Effective Size of the model that is Within 1\" . Line of Sight is blocked. Exception: If both the attacker and the target are Within 1\" of the same terrain piece and Within 3\" of each other, resolve Line of Sight normally.\n\n• Elevation Dead Zone: A model on HIGH GROUND (Size 3+) cannot see a model at GROUND LEVEL that is Within 1\" of the base of the same terrain piece, and vice versa. The same Close Quarters exception applies.\n\nEach terrain piece is assessed independently. Terrain pieces do not combine their Effective Size or proximity. If no single terrain piece meets the requirements for Full Cover or Direct Cover , Line of Sight is not blocked regardless of how many terrain pieces the trace passes through.\n\nA terrain piece's footprint is defined by its physical base or outermost edges viewed from above. Gaps, windows, doorways, and open interiors within the footprint do block the Line of Sight unless players agree otherwise during Battlefield Setup (Part 7.1 ).\n\n Flying models ignore the Full Cover rule. Direct Cover and the Elevation Dead Zone still apply. Treat a Flying model's Effective Size as higher than the Effective Size of any terrain piece on the table (Part 7.1.4 ).\n\n Line of Sight is reciprocal: if Model A can see Model B, Model B can see Model A through the same trace.",
  }
};

export const KEYWORD_SCHEMA_NOTES = {
  purpose: 'Canonical glossary/index layer extracted from Part 11 of the rules.',
  status: 'generated-from-rules',
  guidance: 'Descriptions are sourced from PART_11_KEYWORD_GLOSSARY_AND_DEFINITIONS.html via the generated reference files.',
};
