import { GENERATED_RULES_CONTENT } from './generated-rules-content.js';
import { mergeGeneratedCollection } from './generated-content-merge.js';
import { GENERATED_RULES_DETAIL_CONTENT } from './generated-rules-detail-content.js';
import { mergeGeneratedOwnedCollection } from './generated-owned-merge.js';

/**
 * StarCraft TMG - Protoss faction content starter file
 */

export const PROTOSS_FACTION_CARDS = [
  {
    id: 'protoss-daelaam',
    faction: 'Protoss',
    factionTags: ['Protoss', 'Daelaam'],
    name: 'Daelaam',
    unique: true,
    resourceType: 'EN',
    resourceValue: 1,
    startingSlots: { elite: 1, core: 3, support: 1 },
    abilityIds: ['protoss-daelaam-daeuhl', 'protoss-daelaam-mass-recall'],
    sourceRefs: ['SRC-PROTOSS', 'card:daelaam'],
    notes: null,
  },
  {
    id: 'protoss-khalai',
    faction: 'Protoss',
    factionTags: ['Protoss', 'Khalai'],
    name: 'Khalai',
    unique: true,
    resourceType: 'EN',
    resourceValue: 1,
    startingSlots: { hero: 1, elite: 2, core: 3 },
    abilityIds: ['protoss-khalai-pylon-warp-in', 'protoss-khalai-bound-by-the-khala'],
    sourceRefs: ['SRC-PROTOSS', 'card:khalai'],
    notes: null,
  },
];

export const PROTOSS_UNITS = [
  {
    id: 'protoss-adept',
    faction: 'Protoss',
    factionTags: ['Protoss'],
    name: 'Adept',
    unique: false,
    role: 'Core',
    stats: {
      shield: '2',
      speed: '5/8',
      evade: '5+',
      armour: '5+',
      hp: 3,
      size: 2,
    },
    supplyProfile: [
      { models: '4', supply: 1 },
    ],
    combatTags: ['Biological', 'Light', 'Ground'],
    mineralCost: 150,
    gasCost: 0,
    baseSizeMm: null,
    weaponIds: ['protoss-adept-glaive-cannon', 'protoss-adept-strike'],
    abilityIds: ['protoss-adept-psionic-presence'],
    upgradeRefs: [
      'protoss-adept-glaive-strike',
      'protoss-adept-guidance',
      'protoss-adept-resonating-glaives',
    ],
    sourceRefs: ['SRC-PROTOSS', 'card:adept'],
    notes: 'Starter source-grounded unit example.',
  },
];

export const PROTOSS_WEAPONS = [
  {
    id: 'protoss-adept-glaive-cannon',
    unitId: 'protoss-adept',
    name: 'Glaive Cannon',
    phase: 'Assault Phase',
    range: '8',
    target: 'All',
    roa: 2,
    hit: '3+',
    surgeType: 'Light',
    surgeDice: 'D3+1',
    damage: 1,
    keywordIds: [],
    rulesText: null,
    sourceRefs: ['SRC-PROTOSS', 'card:adept'],
    notes: null,
  },
  {
    id: 'protoss-adept-strike',
    unitId: 'protoss-adept',
    name: 'Strike',
    phase: 'Combat Phase',
    range: 'E',
    target: 'Ground',
    roa: 1,
    hit: '4+',
    surgeType: null,
    surgeDice: null,
    damage: 1,
    keywordIds: [],
    rulesText: null,
    sourceRefs: ['SRC-PROTOSS', 'card:adept'],
    notes: null,
  },
];

export const PROTOSS_ABILITIES = [
  {
    id: 'protoss-daelaam-daeuhl',
    ownerType: 'Faction Card',
    ownerId: 'protoss-daelaam',
    name: "Dae'Uhl",
    phaseLimit: 'Any Phase',
    type: 'Reaction',
    cost: null,
    trigger: 'When a Friendly Unit receives Damage',
    text: 'When a Friendly Unit receives Damage, reduce the Total Damage by 2 (to a minimum of 1).',
    keywordIds: [],
    sourceRefs: ['SRC-PROTOSS', 'card:daelaam'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
  {
    id: 'protoss-daelaam-mass-recall',
    ownerType: 'Faction Card',
    ownerId: 'protoss-daelaam',
    name: 'Mass Recall',
    phaseLimit: 'Movement Phase',
    type: 'Active',
    cost: null,
    trigger: null,
    text: 'Once per Game. Place a Faction Indicator anywhere on the battlefield. All Friendly Protoss Units Within 6" of this Faction Indicator are removed from the battlefield and placed in Reserves.',
    keywordIds: ['place', 'within', 'reserves'],
    sourceRefs: ['SRC-PROTOSS', 'card:daelaam'],
    oncePerRound: false,
    oncePerGame: true,
    notes: null,
  },
  {
    id: 'protoss-khalai-pylon-warp-in',
    ownerType: 'Faction Card',
    ownerId: 'protoss-khalai',
    name: 'Pylon Warp-In',
    phaseLimit: 'Movement Phase',
    type: 'Active',
    cost: null,
    trigger: 'If there is no Friendly Pylon on the battlefield',
    text: 'If there is no Friendly Pylon on the battlefield, place a Friendly Pylon Unit anywhere on the GROUND LEVEL of the battlefield more than 10" away from any Enemy model. This Round, the Pylon is not eligible to use its Special Abilities (excluding Structure).',
    keywordIds: ['place'],
    sourceRefs: ['SRC-PROTOSS', 'card:khalai'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
  {
    id: 'protoss-khalai-bound-by-the-khala',
    ownerType: 'Faction Card',
    ownerId: 'protoss-khalai',
    name: 'Bound by the Khala',
    phaseLimit: 'Movement Phase',
    type: 'Active',
    cost: null,
    trigger: 'At the end of the active Unit’s Activation',
    text: 'At the end of the active Unit’s Activation, select one other Friendly Unit eligible to Activate in the current Phase. Immediately Activate that Unit.',
    keywordIds: [],
    sourceRefs: ['SRC-PROTOSS', 'card:khalai'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
  {
    id: 'protoss-adept-psionic-presence',
    ownerType: 'Unit',
    ownerId: 'protoss-adept',
    name: 'Psionic Presence',
    phaseLimit: 'Any Phase',
    type: 'Passive',
    cost: null,
    trigger: null,
    text: 'All Weapons of Friendly Units targeting an Enemy Unit Within 4" of this Unit’s Shade token gain PRECISION (1).',
    keywordIds: ['within', 'precision'],
    sourceRefs: ['SRC-PROTOSS', 'card:adept'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
];

export const PROTOSS_TACTICAL_CARDS = [
  {
    id: 'gateway',
    faction: 'Protoss',
    factionTags: ['Protoss'],
    name: 'Gateway',
    gasCost: 25,
    sourceRefs: ['PART-12.11', 'card:gateway'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'warp-gate',
    faction: 'Protoss',
    factionTags: ['Protoss'],
    name: 'Warp Gate',
    gasCost: 40,
    sourceRefs: ['PART-12.11', 'card:warp-gate'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'gate-chronoboosted',
    faction: 'Protoss',
    factionTags: ['Protoss'],
    name: 'Gate Chronoboosted',
    gasCost: 40,
    sourceRefs: ['PART-12.11', 'card:gate-chronoboosted'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'observer',
    faction: 'Protoss',
    factionTags: ['Protoss'],
    name: 'Observer',
    gasCost: 25,
    sourceRefs: ['PART-12.11', 'card:observer'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'nexus',
    faction: 'Protoss',
    factionTags: ['Protoss'],
    name: 'Nexus',
    gasCost: 35,
    sourceRefs: ['PART-12.11', 'card:nexus'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'overcharged-nexus',
    faction: 'Protoss',
    factionTags: ['Protoss'],
    name: 'Nexus Overcharged',
    gasCost: 35,
    sourceRefs: ['PART-12.11', 'card:nexus-overcharged'],
    notes: 'Part 12 names this card "Nexus Overcharged"; id kept compatible with the current builder.',
  },
  {
    id: 'power-field',
    faction: 'Protoss',
    factionTags: ['Protoss'],
    name: 'Power Field',
    gasCost: 40,
    sourceRefs: ['PART-12.11', 'card:power-field'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'forge',
    faction: 'Protoss',
    factionTags: ['Protoss'],
    name: 'Forge',
    gasCost: 30,
    sourceRefs: ['PART-12.11', 'card:forge'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'warp-prism',
    faction: 'Protoss',
    factionTags: ['Protoss'],
    name: 'Warp Prism',
    gasCost: 45,
    sourceRefs: ['PART-12.11', 'card:warp-prism'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'twilight-council',
    faction: 'Protoss',
    factionTags: ['Protoss'],
    name: 'Twilight Council',
    gasCost: 40,
    sourceRefs: ['PART-12.11', 'card:twilight-council'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
];
export const PROTOSS_UPGRADES = [
  {
    id: 'protoss-adept-glaive-strike',
    unitId: 'protoss-adept',
    name: 'Glaive Strike',
    phase: 'Any Phase',
    type: 'Upgrade',
    cost: '20',
    specialist: false,
    replacesWeapon: 'Strike',
    text: 'Upgrade cost and availability sourced from Part 12 quick reference.',
    keywordIds: [],
    sourceRefs: ['PART-12.10', 'card:adept'],
    notes: 'Part 12 lists this replacement upgrade at 20 Minerals for the 4-model Adept composition.',
  },
  {
    id: 'protoss-adept-guidance',
    unitId: 'protoss-adept',
    name: 'Guidance',
    phase: 'Any Phase',
    type: 'Upgrade',
    cost: '10',
    specialist: false,
    replacesWeapon: null,
    text: 'Upgrade cost and availability sourced from Part 12 quick reference.',
    keywordIds: [],
    sourceRefs: ['PART-12.10', 'card:adept'],
    notes: 'Part 12 lists this upgrade at 10 Minerals for the 4-model Adept composition.',
  },
  {
    id: 'protoss-adept-resonating-glaives',
    unitId: 'protoss-adept',
    name: 'Resonating Glaives',
    phase: 'Any Phase',
    type: 'Upgrade',
    cost: '20',
    specialist: false,
    replacesWeapon: null,
    text: 'Upgrade cost and availability sourced from Part 12 quick reference.',
    keywordIds: [],
    sourceRefs: ['PART-12.10', 'card:adept'],
    notes: 'Part 12 lists this upgrade at 20 Minerals for the 4-model Adept composition.',
  },
];

mergeGeneratedCollection(PROTOSS_FACTION_CARDS, GENERATED_RULES_CONTENT.protoss?.factionCards);
mergeGeneratedCollection(PROTOSS_UNITS, GENERATED_RULES_CONTENT.protoss?.units);
mergeGeneratedCollection(PROTOSS_TACTICAL_CARDS, GENERATED_RULES_CONTENT.protoss?.tacticalCards);
mergeGeneratedOwnedCollection(PROTOSS_UPGRADES, GENERATED_RULES_CONTENT.protoss?.upgrades, 'unitId');
mergeGeneratedCollection(PROTOSS_FACTION_CARDS, GENERATED_RULES_DETAIL_CONTENT.protoss?.factionCardPatches);
mergeGeneratedCollection(PROTOSS_UNITS, GENERATED_RULES_DETAIL_CONTENT.protoss?.unitPatches);
mergeGeneratedCollection(PROTOSS_TACTICAL_CARDS, GENERATED_RULES_DETAIL_CONTENT.protoss?.tacticalCardPatches);
mergeGeneratedOwnedCollection(PROTOSS_UPGRADES, GENERATED_RULES_DETAIL_CONTENT.protoss?.upgrades, 'unitId', ['phase']);
mergeGeneratedOwnedCollection(PROTOSS_WEAPONS, GENERATED_RULES_DETAIL_CONTENT.protoss?.weapons, 'unitId', ['phase']);
mergeGeneratedOwnedCollection(PROTOSS_ABILITIES, GENERATED_RULES_DETAIL_CONTENT.protoss?.abilities, 'ownerId', ['phaseLimit']);

export const PROTOSS_CONTENT = {
  faction: 'Protoss',
  factionCards: PROTOSS_FACTION_CARDS,
  units: PROTOSS_UNITS,
  weapons: PROTOSS_WEAPONS,
  abilities: PROTOSS_ABILITIES,
  tacticalCards: PROTOSS_TACTICAL_CARDS,
  upgrades: PROTOSS_UPGRADES,
};
