import { GENERATED_RULES_CONTENT } from './generated-rules-content.js';
import { mergeGeneratedCollection } from './generated-content-merge.js';
import { GENERATED_RULES_DETAIL_CONTENT } from './generated-rules-detail-content.js';
import { mergeGeneratedOwnedCollection } from './generated-owned-merge.js';

/**
 * StarCraft TMG - Terran faction content starter file
 */

export const TERRAN_FACTION_CARDS = [
  {
    id: 'terran-raynors-raiders',
    faction: 'Terran',
    factionTags: ['Terran', "Raynor's Raiders"],
    name: "Raynor's Raiders",
    unique: true,
    resourceType: 'CP',
    resourceValue: 1,
    startingSlots: { hero: 1, core: 3, support: 1 },
    abilityIds: ['terran-raynors-raiders-rapid-reinforcements', 'terran-raynors-raiders-ready-for-pickup'],
    sourceRefs: ['SRC-TERRAN', 'card:raynors-raiders'],
    notes: null,
  },
  {
    id: 'terran-armed-forces',
    faction: 'Terran',
    factionTags: ['Terran', 'Terran Armed Forces'],
    name: 'Terran Armed Forces',
    unique: true,
    resourceType: 'CP',
    resourceValue: 1,
    startingSlots: { elite: 1, core: 3, support: 1 },
    abilityIds: ['terran-armed-forces-tactical-retreat', 'terran-armed-forces-terran-tenacity'],
    sourceRefs: ['SRC-TERRAN', 'card:terran-armed-forces'],
    notes: null,
  },
];

export const TERRAN_UNITS = [
  {
    id: 'terran-goliath',
    faction: 'Terran',
    factionTags: ['Terran'],
    name: 'Goliath',
    unique: false,
    role: 'Elite',
    stats: {
      shield: null,
      speed: '7',
      evade: '-',
      armour: '4+',
      hp: 10,
      size: 3,
    },
    supplyProfile: [
      { models: '1', supply: 2 },
    ],
    combatTags: ['Armoured', 'Mechanical', 'Ground'],
    mineralCost: 190,
    gasCost: 0,
    baseSizeMm: null,
    weaponIds: [
      'terran-goliath-autocannon',
      'terran-goliath-underbelly-machine-gun',
      'terran-goliath-hellfire-missiles',
      'terran-goliath-stomp',
    ],
    abilityIds: [],
    upgradeRefs: [
      'terran-goliath-ares-class-targeting-system',
      'terran-goliath-haywire-missiles',
      'terran-goliath-scatter-missiles',
    ],
    sourceRefs: ['SRC-TERRAN', 'card:goliath'],
    notes: 'Starter source-grounded unit example.',
  },
];

export const TERRAN_WEAPONS = [
  {
    id: 'terran-goliath-autocannon',
    unitId: 'terran-goliath',
    name: 'Autocannon',
    phase: 'Assault Phase',
    range: '12',
    target: 'Ground',
    roa: 9,
    hit: '4+',
    surgeType: null,
    surgeDice: null,
    damage: 1,
    keywordIds: [],
    rulesText: null,
    sourceRefs: ['SRC-TERRAN', 'card:goliath'],
    notes: null,
  },
  {
    id: 'terran-goliath-underbelly-machine-gun',
    unitId: 'terran-goliath',
    name: 'Underbelly Machine Gun',
    phase: 'Assault Phase',
    range: '8',
    target: 'Ground',
    roa: 6,
    hit: '3+',
    surgeType: 'Light',
    surgeDice: 'D3',
    damage: 1,
    keywordIds: [],
    rulesText: null,
    sourceRefs: ['SRC-TERRAN', 'card:goliath'],
    notes: null,
  },
  {
    id: 'terran-goliath-hellfire-missiles',
    unitId: 'terran-goliath',
    name: 'Hellfire Missiles',
    phase: 'Assault Phase',
    range: '16',
    target: 'Flying',
    roa: 6,
    hit: '3+',
    surgeType: 'Light',
    surgeDice: 'D3',
    damage: 1,
    keywordIds: [],
    rulesText: null,
    sourceRefs: ['SRC-TERRAN', 'card:goliath'],
    notes: null,
  },
  {
    id: 'terran-goliath-stomp',
    unitId: 'terran-goliath',
    name: 'Stomp',
    phase: 'Combat Phase',
    range: 'E',
    target: 'Ground',
    roa: 4,
    hit: '5+',
    surgeType: null,
    surgeDice: null,
    damage: 1,
    keywordIds: [],
    rulesText: null,
    sourceRefs: ['SRC-TERRAN', 'card:goliath'],
    notes: null,
  },
];

export const TERRAN_ABILITIES = [
  {
    id: 'terran-raynors-raiders-rapid-reinforcements',
    ownerType: 'Faction Card',
    ownerId: 'terran-raynors-raiders',
    name: 'Rapid Reinforcements',
    phaseLimit: 'Movement Phase',
    type: 'Active',
    cost: null,
    trigger: null,
    text: 'Place a Friendly Point Defence Drone Unit anywhere on the battlefield, more than 1" away from any Enemy model. Remove this Unit at the End of the Round.',
    keywordIds: ['place'],
    sourceRefs: ['SRC-TERRAN', 'card:raynors-raiders'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
  {
    id: 'terran-raynors-raiders-ready-for-pickup',
    ownerType: 'Faction Card',
    ownerId: 'terran-raynors-raiders',
    name: 'Ready for Pickup?',
    phaseLimit: 'Movement Phase',
    type: 'Active',
    cost: null,
    trigger: null,
    text: 'Once per Game. The active Unit resolves the PLACE (12) effect. Models placed by this effect cannot be set up Within the Engagement Range of any Enemy Unit. This resolves instead of performing a standard action.',
    keywordIds: ['place', 'within'],
    sourceRefs: ['SRC-TERRAN', 'card:raynors-raiders'],
    oncePerRound: false,
    oncePerGame: true,
    notes: null,
  },
  {
    id: 'terran-armed-forces-tactical-retreat',
    ownerType: 'Faction Card',
    ownerId: 'terran-armed-forces',
    name: 'Tactical Retreat',
    phaseLimit: 'Movement Phase',
    type: 'Active',
    cost: null,
    trigger: null,
    text: 'The active Unit ignores the Disengage penalty for the remainder of the Round.',
    keywordIds: ['disengage'],
    sourceRefs: ['SRC-TERRAN', 'card:terran-armed-forces'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
  {
    id: 'terran-armed-forces-terran-tenacity',
    ownerType: 'Faction Card',
    ownerId: 'terran-armed-forces',
    name: 'Terran Tenacity',
    phaseLimit: 'Movement Phase',
    type: 'Active',
    cost: null,
    trigger: null,
    text: 'Once per Game. Immediately claim the First Player Marker. No other player may claim the First Player Marker for the remainder of this Phase.',
    keywordIds: ['first-player-marker'],
    sourceRefs: ['SRC-TERRAN', 'card:terran-armed-forces'],
    oncePerRound: false,
    oncePerGame: true,
    notes: null,
  },
];

export const TERRAN_TACTICAL_CARDS = [
  {
    id: 'barracks',
    faction: 'Terran',
    factionTags: ['Terran'],
    name: 'Barracks',
    gasCost: 25,
    sourceRefs: ['PART-12.11', 'card:barracks'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'barracks-proxy',
    faction: 'Terran',
    factionTags: ['Terran'],
    name: 'Barracks (Proxy)',
    gasCost: 40,
    sourceRefs: ['PART-12.11', 'card:barracks-proxy'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'barracks-tech-lab',
    faction: 'Terran',
    factionTags: ['Terran'],
    name: 'Barracks (Tech Lab)',
    gasCost: 45,
    sourceRefs: ['PART-12.11', 'card:barracks-tech-lab'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'supply-depot',
    faction: 'Terran',
    factionTags: ['Terran'],
    name: 'Supply Depot',
    gasCost: 40,
    sourceRefs: ['PART-12.11', 'card:supply-depot'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'factory',
    faction: 'Terran',
    factionTags: ['Terran'],
    name: 'Factory',
    gasCost: 35,
    sourceRefs: ['PART-12.11', 'card:factory'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'engineering-bay',
    faction: 'Terran',
    factionTags: ['Terran'],
    name: 'Engineering Bay',
    gasCost: 30,
    sourceRefs: ['PART-12.11', 'card:engineering-bay'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'armory',
    faction: 'Terran',
    factionTags: ['Terran'],
    name: 'Armory',
    gasCost: 30,
    sourceRefs: ['PART-12.11', 'card:armory'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'academy',
    faction: 'Terran',
    factionTags: ['Terran'],
    name: 'Academy',
    gasCost: 35,
    sourceRefs: ['PART-12.11', 'card:academy'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'orbital-command',
    faction: 'Terran',
    factionTags: ['Terran'],
    name: 'Orbital Command',
    gasCost: 25,
    sourceRefs: ['PART-12.11', 'card:orbital-command'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'dropship',
    faction: 'Terran',
    factionTags: ['Terran'],
    name: 'Dropship',
    gasCost: 40,
    sourceRefs: ['PART-12.11', 'card:dropship'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
];

export const TERRAN_UPGRADES = [
  {
    id: 'terran-goliath-ares-class-targeting-system',
    unitId: 'terran-goliath',
    name: 'Ares-Class Targeting System',
    phase: 'Any Phase',
    type: 'Upgrade',
    cost: '20',
    specialist: false,
    replacesWeapon: null,
    text: 'Upgrade cost and availability sourced from Part 12 quick reference.',
    keywordIds: [],
    sourceRefs: ['PART-12.10', 'card:goliath'],
    notes: 'Part 12 lists this upgrade at 20 Minerals for the 1-model Goliath composition.',
  },
  {
    id: 'terran-goliath-haywire-missiles',
    unitId: 'terran-goliath',
    name: 'Haywire Missiles',
    phase: 'Any Phase',
    type: 'Upgrade',
    cost: '40',
    specialist: false,
    replacesWeapon: 'Hellfire Missiles',
    text: 'Upgrade cost and availability sourced from Part 12 quick reference.',
    keywordIds: [],
    sourceRefs: ['PART-12.10', 'card:goliath'],
    notes: 'Part 12 lists this replacement upgrade at 40 Minerals for the 1-model Goliath composition.',
  },
  {
    id: 'terran-goliath-scatter-missiles',
    unitId: 'terran-goliath',
    name: 'Scatter Missiles',
    phase: 'Any Phase',
    type: 'Upgrade',
    cost: '30',
    specialist: false,
    replacesWeapon: 'Hellfire Missiles',
    text: 'Upgrade cost and availability sourced from Part 12 quick reference.',
    keywordIds: [],
    sourceRefs: ['PART-12.10', 'card:goliath'],
    notes: 'Part 12 lists this replacement upgrade at 30 Minerals for the 1-model Goliath composition.',
  },
  {
    id: 'terran-marine-combat-shield',
    unitId: 'terran-marine',
    name: 'Combat Shield',
    phase: 'Movement Phase',
    type: 'Active',
    cost: '20/30',
    specialist: false,
    replacesWeapon: null,
    text: 'This Unit is always eligible to make an Evade Roll against any Close Combat Attack targeting it and any Damage from an Enemy Special Ability.',
    keywordIds: [],
    sourceRefs: ['SRC-TERRAN', 'card:marine'],
    notes: 'Source-grounded upgrade example; owning unit data can be added later.',
  },
  {
    id: 'terran-marine-agg-12',
    unitId: 'terran-marine',
    name: 'AGG-12',
    phase: 'Assault Phase',
    type: 'Upgrade',
    cost: '10',
    specialist: true,
    replacesWeapon: 'C-14 Rifle',
    text: 'Replacement ranged weapon upgrade.',
    keywordIds: ['long-range', 'specialist'],
    sourceRefs: ['SRC-TERRAN', 'card:marine'],
    notes: 'Weapon stats are on the card table; text kept minimal because this upgrade primarily changes the weapon profile.',
  },
  {
    id: 'terran-marine-rocket-launcher',
    unitId: 'terran-marine',
    name: 'Rocket Launcher',
    phase: 'Assault Phase',
    type: 'Upgrade',
    cost: '40',
    specialist: true,
    replacesWeapon: null,
    text: 'Specialist ranged weapon upgrade.',
    keywordIds: ['indirect-fire', 'long-range', 'sidearm', 'specialist'],
    sourceRefs: ['SRC-TERRAN', 'card:marine'],
    notes: 'Weapon stats are on the card table; text kept minimal because this upgrade primarily changes the weapon profile.',
  },
  {
    id: 'terran-marine-slugthrower',
    unitId: 'terran-marine',
    name: 'Slugthrower',
    phase: 'Assault Phase',
    type: 'Passive',
    cost: '10/20',
    specialist: false,
    replacesWeapon: null,
    text: 'When this Unit makes a Ranged Attack with a C-14 Rifle and the target is Within 8", that weapon gains ANTI-EVADE (1).',
    keywordIds: ['anti-evade', 'within'],
    sourceRefs: ['SRC-TERRAN', 'card:marine'],
    notes: null,
  },
  {
    id: 'terran-marine-grenades-frag',
    unitId: 'terran-marine',
    name: 'Grenades - Frag',
    phase: 'Assault Phase',
    type: 'Passive',
    cost: '10',
    specialist: false,
    replacesWeapon: null,
    text: 'When this Unit makes a Ranged Attack with a C-14 Rifle and the target is Within 8", that weapon’s S Dice is replaced by D6.',
    keywordIds: ['within'],
    sourceRefs: ['SRC-TERRAN', 'card:marine'],
    notes: null,
  },
];

mergeGeneratedCollection(TERRAN_FACTION_CARDS, GENERATED_RULES_CONTENT.terran?.factionCards);
mergeGeneratedCollection(TERRAN_UNITS, GENERATED_RULES_CONTENT.terran?.units);
mergeGeneratedCollection(TERRAN_TACTICAL_CARDS, GENERATED_RULES_CONTENT.terran?.tacticalCards);
mergeGeneratedOwnedCollection(TERRAN_UPGRADES, GENERATED_RULES_CONTENT.terran?.upgrades, 'unitId');
mergeGeneratedCollection(TERRAN_FACTION_CARDS, GENERATED_RULES_DETAIL_CONTENT.terran?.factionCardPatches);
mergeGeneratedCollection(TERRAN_UNITS, GENERATED_RULES_DETAIL_CONTENT.terran?.unitPatches);
mergeGeneratedCollection(TERRAN_TACTICAL_CARDS, GENERATED_RULES_DETAIL_CONTENT.terran?.tacticalCardPatches);
mergeGeneratedOwnedCollection(TERRAN_UPGRADES, GENERATED_RULES_DETAIL_CONTENT.terran?.upgrades, 'unitId', ['phase']);
mergeGeneratedOwnedCollection(TERRAN_WEAPONS, GENERATED_RULES_DETAIL_CONTENT.terran?.weapons, 'unitId', ['phase']);
mergeGeneratedOwnedCollection(TERRAN_ABILITIES, GENERATED_RULES_DETAIL_CONTENT.terran?.abilities, 'ownerId', ['phaseLimit']);

export const TERRAN_CONTENT = {
  faction: 'Terran',
  factionCards: TERRAN_FACTION_CARDS,
  units: TERRAN_UNITS,
  weapons: TERRAN_WEAPONS,
  abilities: TERRAN_ABILITIES,
  tacticalCards: TERRAN_TACTICAL_CARDS,
  upgrades: TERRAN_UPGRADES,
};
