import { GENERATED_RULES_CONTENT } from './generated-rules-content.js';
import { mergeGeneratedCollection } from './generated-content-merge.js';
import { GENERATED_RULES_DETAIL_CONTENT } from './generated-rules-detail-content.js';
import { mergeGeneratedOwnedCollection } from './generated-owned-merge.js';

/**
 * StarCraft TMG - Zerg faction content starter file
 *
 * This file is the Zerg-side entry point for data entry.
 * It uses the same object shapes defined by the shared schema files,
 * but keeps Zerg records grouped together for easier editing and audit.
 */

export const ZERG_FACTION_CARDS = [
  {
    id: 'zerg-kerrigans-swarm',
    faction: 'Zerg',
    factionTags: ['Zerg', "Kerrigan's Swarm"],
    name: "Kerrigan's Swarm",
    unique: true,
    resourceType: 'BM',
    resourceValue: 1,
    startingSlots: { hero: 1, elite: 2, core: 3 },
    abilityIds: [
      'zerg-kerrigans-swarm-wild-mutation',
      'zerg-kerrigans-swarm-zerg-creep',
      'zerg-kerrigans-swarm-omega-network',
    ],
    sourceRefs: ['SRC-ZERG', 'card:kerrigans-swarm'],
    notes: null,
  },
  {
    id: 'zerg-zerg-swarm',
    faction: 'Zerg',
    factionTags: ['Zerg', 'Zerg Swarm'],
    name: 'Zerg Swarm',
    unique: true,
    resourceType: 'BM',
    resourceValue: 1,
    startingSlots: { elite: 1, core: 3, support: 1 },
    abilityIds: [
      'zerg-zerg-swarm-brood-instinct',
      'zerg-zerg-swarm-zerg-creep',
      'zerg-zerg-swarm-rapid-burrowing',
    ],
    sourceRefs: ['SRC-ZERG', 'card:zerg-swarm'],
    notes: null,
  },
];

export const ZERG_UNITS = [
  {
    id: 'zerg-corpser-roach',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Corpser (Roach)',
    unique: false,
    role: 'Core',
    stats: {
      shield: null,
      speed: '4/7',
      evade: '5+',
      armour: '3+',
      hp: 4,
      size: 2,
    },
    supplyProfile: [
      { models: '3', supply: 1 },
    ],
    combatTags: ['Armoured', 'Biological', 'Ground'],
    mineralCost: 250,
    gasCost: 0,
    baseSizeMm: null,
    weaponIds: ['zerg-corpser-acid-saliva', 'zerg-corpser-claws'],
    abilityIds: ['zerg-corpser-burrow'],
    upgradeRefs: [
      'zerg-corpser-burrow-ambush',
      'zerg-corpser-glial-reconstitution',
      'zerg-corpser-hydriodic-bile',
      'zerg-corpser-tunneling-claws',
    ],
    sourceRefs: ['SRC-ZERG', 'card:corpser-roach'],
    notes: 'Starter source-grounded unit example.',
  },
];

export const ZERG_WEAPONS = [
  {
    id: 'zerg-corpser-acid-saliva',
    unitId: 'zerg-corpser-roach',
    name: 'Acid Saliva',
    phase: 'Assault Phase',
    range: '8',
    target: 'Ground',
    roa: 2,
    hit: '3+',
    surgeType: null,
    surgeDice: null,
    damage: 1,
    keywordIds: [],
    rulesText: null,
    sourceRefs: ['SRC-ZERG', 'card:corpser-roach'],
    notes: null,
  },
  {
    id: 'zerg-corpser-claws',
    unitId: 'zerg-corpser-roach',
    name: 'Claws',
    phase: 'Combat Phase',
    range: 'E',
    target: 'Ground',
    roa: 3,
    hit: '4+',
    surgeType: 'Light',
    surgeDice: 'D3+1',
    damage: 1,
    keywordIds: [],
    rulesText: null,
    sourceRefs: ['SRC-ZERG', 'card:corpser-roach'],
    notes: null,
  },
];

export const ZERG_ABILITIES = [
  {
    id: 'zerg-kerrigans-swarm-wild-mutation',
    ownerType: 'Faction Card',
    ownerId: 'zerg-kerrigans-swarm',
    name: 'Wild Mutation',
    phaseLimit: 'Any Phase',
    type: 'Active',
    cost: null,
    trigger: 'If the active Unit is ON CREEP',
    text: 'If the active Unit is ON CREEP, the Unit gains BUFF Speed (1) and its first Weapon used gains PRECISION (1).',
    keywordIds: ['buff', 'precision', 'on-creep'],
    sourceRefs: ['SRC-ZERG', 'card:kerrigans-swarm'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
  {
    id: 'zerg-kerrigans-swarm-zerg-creep',
    ownerType: 'Faction Card',
    ownerId: 'zerg-kerrigans-swarm',
    name: 'Zerg Creep',
    phaseLimit: 'Any Phase',
    type: 'Passive',
    cost: null,
    trigger: 'During Army Building',
    text: 'During Army Building, select exactly one Creep Card and add it to their Army List, paying its listed cost (if any).',
    keywordIds: [],
    sourceRefs: ['SRC-ZERG', 'card:kerrigans-swarm'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
  {
    id: 'zerg-kerrigans-swarm-omega-network',
    ownerType: 'Faction Card',
    ownerId: 'zerg-kerrigans-swarm',
    name: 'Omega Network',
    phaseLimit: 'Movement Phase',
    type: 'Active',
    cost: null,
    trigger: 'If there is no Friendly Omega Worm on the battlefield',
    text: 'If there is no Friendly Omega Worm on the battlefield, place a Friendly Omega Worm Unit anywhere on GROUND LEVEL of the battlefield, more than 10" away from any Enemy model. This Round, the Omega Worm is not eligible to use its Special Abilities (excluding Structure).',
    keywordIds: ['place'],
    sourceRefs: ['SRC-ZERG', 'card:kerrigans-swarm'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
  {
    id: 'zerg-zerg-swarm-brood-instinct',
    ownerType: 'Faction Card',
    ownerId: 'zerg-zerg-swarm',
    name: 'Brood Instinct',
    phaseLimit: 'Any Phase',
    type: 'Reaction',
    cost: null,
    trigger: 'Use before a Friendly Unit makes an Evade Roll',
    text: 'Use before a Friendly Unit makes an Evade Roll. Apply a +1 Modifier to that roll.',
    keywordIds: [],
    sourceRefs: ['SRC-ZERG', 'card:zerg-swarm'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
  {
    id: 'zerg-zerg-swarm-zerg-creep',
    ownerType: 'Faction Card',
    ownerId: 'zerg-zerg-swarm',
    name: 'Zerg Creep',
    phaseLimit: 'Any Phase',
    type: 'Passive',
    cost: null,
    trigger: 'During Army Building',
    text: 'During Army Building, select exactly one Creep Card and add it to their Army List, paying its listed cost (if any).',
    keywordIds: [],
    sourceRefs: ['SRC-ZERG', 'card:zerg-swarm'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
  {
    id: 'zerg-zerg-swarm-rapid-burrowing',
    ownerType: 'Faction Card',
    ownerId: 'zerg-zerg-swarm',
    name: 'Rapid Burrowing',
    phaseLimit: 'Movement Phase',
    type: 'Active',
    cost: null,
    trigger: null,
    text: 'Select one Friendly, Unengaged Ground Zerg Unit on the battlefield. That Unit gains the Burrowed Status, even if it has already been Activated this Round.',
    keywordIds: ['burrowed'],
    sourceRefs: ['SRC-ZERG', 'card:zerg-swarm'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
  {
    id: 'zerg-corpser-burrow',
    ownerType: 'Unit',
    ownerId: 'zerg-corpser-roach',
    name: 'Burrow',
    phaseLimit: 'Any Phase',
    type: 'Active',
    cost: '2 BM',
    trigger: 'If this Unit is Unengaged',
    text: 'If this Unit is Unengaged, it gains or loses the Burrowed Status.',
    keywordIds: ['burrowed'],
    sourceRefs: ['SRC-ZERG', 'card:corpser-roach'],
    oncePerRound: false,
    oncePerGame: false,
    notes: null,
  },
];

export const ZERG_TACTICAL_CARDS = [
  {
    id: 'spawning-pool',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Spawning Pool',
    gasCost: 25,
    sourceRefs: ['PART-12.11', 'card:spawning-pool'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'spawning-pool-six',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Spawning Pool (Six Pool)',
    gasCost: 40,
    sourceRefs: ['PART-12.11', 'card:spawning-pool-six-pool'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'roach-warren',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Roach Warren',
    gasCost: 25,
    sourceRefs: ['PART-12.11', 'card:roach-warren'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'hydralisk-den',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Hydralisk Den',
    gasCost: 35,
    sourceRefs: ['PART-12.11', 'card:hydralisk-den'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'evolution-chamber',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Evolution Chamber',
    gasCost: 30,
    sourceRefs: ['PART-12.11', 'card:evolution-chamber'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'hatchery',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Hatchery',
    gasCost: 30,
    sourceRefs: ['PART-12.11', 'card:hatchery'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'lair',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Lair',
    gasCost: 35,
    sourceRefs: ['PART-12.11', 'card:lair'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'overseer',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Overseer',
    gasCost: 25,
    sourceRefs: ['PART-12.11', 'card:overseer'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'overlord',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Overlord',
    gasCost: 45,
    sourceRefs: ['PART-12.11', 'card:overlord'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'accelerating-creep',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Accelerating Creep',
    gasCost: 0,
    sourceRefs: ['PART-12.11', 'card:accelerating-creep'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
  {
    id: 'malignant-creep',
    faction: 'Zerg',
    factionTags: ['Zerg'],
    name: 'Malignant Creep',
    gasCost: 10,
    sourceRefs: ['PART-12.11', 'card:malignant-creep'],
    notes: 'Gas cost sourced from Part 12.11 quick reference.',
  },
];
export const ZERG_UPGRADES = [
  {
    id: 'zerg-corpser-burrow-ambush',
    unitId: 'zerg-corpser-roach',
    name: 'Burrow Ambush',
    phase: 'Any Phase',
    type: 'Upgrade',
    cost: '20',
    specialist: false,
    replacesWeapon: null,
    text: 'Upgrade cost and availability sourced from Part 12 quick reference.',
    keywordIds: [],
    sourceRefs: ['PART-12.10', 'card:corpser-roach'],
    notes: 'Part 12 lists this upgrade at 20 Minerals for the 3-model Corpser composition.',
  },
  {
    id: 'zerg-corpser-glial-reconstitution',
    unitId: 'zerg-corpser-roach',
    name: 'Glial Reconstitution',
    phase: 'Any Phase',
    type: 'Upgrade',
    cost: '20',
    specialist: false,
    replacesWeapon: null,
    text: 'Upgrade cost and availability sourced from Part 12 quick reference.',
    keywordIds: [],
    sourceRefs: ['PART-12.10', 'card:corpser-roach'],
    notes: 'Part 12 lists this upgrade at 20 Minerals for the 3-model Corpser composition.',
  },
  {
    id: 'zerg-corpser-hydriodic-bile',
    unitId: 'zerg-corpser-roach',
    name: 'Hydriodic Bile',
    phase: 'Any Phase',
    type: 'Upgrade',
    cost: '10',
    specialist: false,
    replacesWeapon: null,
    text: 'Upgrade cost and availability sourced from Part 12 quick reference.',
    keywordIds: [],
    sourceRefs: ['PART-12.10', 'card:corpser-roach'],
    notes: 'Part 12 lists this upgrade at 10 Minerals for the 3-model Corpser composition.',
  },
  {
    id: 'zerg-corpser-tunneling-claws',
    unitId: 'zerg-corpser-roach',
    name: 'Tunneling Claws',
    phase: 'Any Phase',
    type: 'Upgrade',
    cost: '10',
    specialist: false,
    replacesWeapon: null,
    text: 'Upgrade cost and availability sourced from Part 12 quick reference.',
    keywordIds: [],
    sourceRefs: ['PART-12.10', 'card:corpser-roach'],
    notes: 'Part 12 lists this upgrade at 10 Minerals for the 3-model Corpser composition.',
  },
];

mergeGeneratedCollection(ZERG_FACTION_CARDS, GENERATED_RULES_CONTENT.zerg?.factionCards);
mergeGeneratedCollection(ZERG_UNITS, GENERATED_RULES_CONTENT.zerg?.units);
mergeGeneratedCollection(ZERG_TACTICAL_CARDS, GENERATED_RULES_CONTENT.zerg?.tacticalCards);
mergeGeneratedOwnedCollection(ZERG_UPGRADES, GENERATED_RULES_CONTENT.zerg?.upgrades, 'unitId');
mergeGeneratedCollection(ZERG_FACTION_CARDS, GENERATED_RULES_DETAIL_CONTENT.zerg?.factionCardPatches);
mergeGeneratedCollection(ZERG_UNITS, GENERATED_RULES_DETAIL_CONTENT.zerg?.unitPatches);
mergeGeneratedCollection(ZERG_TACTICAL_CARDS, GENERATED_RULES_DETAIL_CONTENT.zerg?.tacticalCardPatches);
mergeGeneratedOwnedCollection(ZERG_UPGRADES, GENERATED_RULES_DETAIL_CONTENT.zerg?.upgrades, 'unitId', ['phase']);
mergeGeneratedOwnedCollection(ZERG_WEAPONS, GENERATED_RULES_DETAIL_CONTENT.zerg?.weapons, 'unitId', ['phase']);
mergeGeneratedOwnedCollection(ZERG_ABILITIES, GENERATED_RULES_DETAIL_CONTENT.zerg?.abilities, 'ownerId', ['phaseLimit']);

export const ZERG_CONTENT = {
  faction: 'Zerg',
  factionCards: ZERG_FACTION_CARDS,
  units: ZERG_UNITS,
  weapons: ZERG_WEAPONS,
  abilities: ZERG_ABILITIES,
  tacticalCards: ZERG_TACTICAL_CARDS,
  upgrades: ZERG_UPGRADES,
};
